# Generated by Django 3.2.4 on 2021-07-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, help_text='Your title will be default slug if you leave it blank', unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, help_text='Write a short description about your post', max_length=500, verbose_name='Descripiton')),
                ('likes', models.PositiveIntegerField(verbose_name='likes')),
                ('content', models.TextField(help_text='Put your actual content here.', verbose_name='content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='update_on')),
                ('thumbnail', models.ImageField(blank=True, help_text='Insert a thumbnail for your blog.', null=True, upload_to='blog', verbose_name='thumbnail')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1, help_text='publish or draft your blog (default=publish)')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your tag name here.', max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='Tag name will be default slug if you leave it blank.', unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
