# Generated by Django 3.2.4 on 2021-07-11 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clap',
            unique_together={('user', 'blog')},
        ),
    ]
