# Generated by Django 3.2.4 on 2021-08-27 04:30

import blog.customvalidators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='update on')),
                ('heart_eyes_count', models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_comment_like], verbose_name='heart eyes')),
                ('thumbsup_count', models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_comment_like], verbose_name='thumbsup')),
                ('thumbsdown_count', models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_comment_like], verbose_name='thumbsdown')),
                ('sunglasses_count', models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_comment_like], verbose_name='sunglasses_count')),
                ('rocket_count', models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_comment_like], verbose_name='rocket')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlikes', to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
