# Generated by Django 3.2.4 on 2021-07-16 15:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Put your actual content here.', null=True, verbose_name='content'),
        ),
    ]
