# Generated by Django 3.2.4 on 2021-07-11 14:02

import blog.customvalidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_clap_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clap',
            name='count',
            field=models.PositiveSmallIntegerField(validators=[blog.customvalidators.validate_clap], verbose_name='count'),
        ),
    ]
