# Generated by Django 3.2.4 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_img',
            field=models.ImageField(default='tags/default_tag.jpg', help_text='Insert a background image for this tag.', upload_to='tags', verbose_name='background image'),
        ),
    ]
