# Generated by Django 3.2.4 on 2021-08-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='compress',
            field=models.BooleanField(default=False),
        ),
    ]
