# Generated by Django 3.2.4 on 2021-08-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_compress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='compress',
            field=models.BooleanField(default=False, help_text='checking this field will enable compression in thumbnail image.', verbose_name='compress thumbnail'),
        ),
    ]
