# Generated by Django 3.2.4 on 2021-08-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_compress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='compress',
            new_name='compress_thumbnail',
        ),
    ]
