# Generated by Django 3.2.4 on 2021-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_compress_blog_compress_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='blog_blog_title_d6be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['description'], name='blog_blog_descrip_a0d3cf_idx'),
        ),
    ]
