# Generated by Django 3.2.4 on 2021-08-04 10:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='package name will be default slug if you leave it blank', unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, help_text='Write a short description about your post', max_length=500, verbose_name='Descripiton')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Put your actual content here.', null=True, verbose_name='content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='update_on')),
                ('thumbnail', models.ImageField(blank=True, help_text='Insert a thumbnail for your package.', null=True, upload_to='package', verbose_name='thumbnail')),
                ('compress_thumbnail', models.BooleanField(default=False, help_text='checking this field will enable compression in thumbnail image.', verbose_name='compress thumbnail')),
                ('price', models.IntegerField(help_text='enter the package price', verbose_name='price')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
