# Generated by Django 3.2.4 on 2021-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='Enter your package name here.', max_length=200, unique=True, verbose_name='name'),
        ),
    ]
