# Generated by Django 3.2.4 on 2021-08-13 02:52

from django.db import migrations, models
import django.db.models.deletion
import package.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_review_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=package.models.upload_gallery_image)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='package.package')),
            ],
        ),
    ]
