# Generated by Django 3.2.4 on 2021-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20210805_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', help_text='choose the difficulty level', max_length=50, verbose_name='difficulty level'),
        ),
    ]
