# Generated by Django 3.2.4 on 2021-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20210813_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarys', to='package.package'),
        ),
    ]
