# Generated by Django 3.2.4 on 2021-08-14 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_itinerary_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveSmallIntegerField(help_text='Information number', validators=[django.core.validators.MinValueValidator(1)], verbose_name='S.N')),
                ('title', models.CharField(help_text='Enter the title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Write a short description', verbose_name='Description')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usefulinformations', to='package.package')),
            ],
            options={
                'ordering': ['package', 'sn'],
                'unique_together': {('package', 'sn')},
            },
        ),
    ]
