# Generated by Django 3.2.4 on 2021-09-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_usefulinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
    ]
