# Generated by Django 3.2.4 on 2021-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentlike'),
        ('package', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(help_text='choose suitable tags for your blog', related_name='packages', to='blog.Tag'),
        ),
    ]
