# Generated by Django 3.2.4 on 2021-09-04 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0008_package_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_person', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total person')),
                ('booked_on', models.DateTimeField(auto_now_add=True, verbose_name='create on')),
                ('payment_method', models.CharField(choices=[('Esewa', 'Esewa'), ('Stripe', 'Stripe')], max_length=15, verbose_name='payment method')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
